apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.employeeservice.name }}-svc
spec:
  selector:
    app: {{ .Values.employeeservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.employeeservice.service.port }}
      targetPort: {{ .Values.employeeservice.service.targetPort }}
      nodePort: {{ .Values.employeeservice.service.nodePort }}
  type: {{ .Values.employeeservice.service.type }}
