apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-svc
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.containerPort }}
