apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeeservice-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employeeservice #This Deployment should manage Pods that have the label app=employeeservice
  template:     # pod configuration
    metadata:
      labels:
        app: employeeservice # This should be same of selector.matchLabels.app
    spec:
      containers:
        - name: employeeservice
          image: employee-service:1.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://employeedb-svc:27017/employeeManagement
